site_name: ConventionTests
theme: readthedocs
repo_url: https://github.com/TestStack/TestStack.ConventionTests

pages:
- Home: index.md
- 'Defining Conventions': 'defining-conventions.md'
- 'Symmetric Conventions': 'symmetric-conventions.md'
- 'Changelog': 'changelog.md'